### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by studiocardo** [Maluuba/frames#8]
Hi

I just downloaded your dataset and the git repository.  

When I executed 
```bash
tracking-evaluate eval Frames-dataset/frames.json ./output/prediction.json 2
```
I got the following err msg:
```
frametracking-evaluate eval Frames-dataset/frames.json ./output/prediction.json 2
Traceback (most recent call last):
  File "/home/shogo/miniconda3/bin/frametracking-evaluate", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/shogo/Projects/Maluuba_frames/bin/frametracking-evaluate", line 105, in <module>
    cli()
  File "/home/shogo/miniconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/shogo/miniconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/shogo/miniconda3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/shogo/miniconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shogo/miniconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/shogo/Projects/Maluuba_frames/bin/frametracking-evaluate", line 64, in eval
    pred_dlgs = pred_dlgs_lst = json.load(results_json)
  File "/home/shogo/miniconda3/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/shogo/miniconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/shogo/miniconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/shogo/miniconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Supposedly this type of error usually suggests an invalid json file format.  And when I do a 
```bash
wc -l frames.json
```
I got 0.  

Has anyone else experienced this problem?

Thx for your help.

Regards,
SH

**Comment by studiocardo** [comment]
BTW, I'm using python 3.6.7.

**Comment by juharris** [comment]
It's normal that frames.json has no newlines to save space.
You can take a peek at it: `less frames.json`.

From the stacktrace, it looks like the problem is with the results file ("prediction.json").
